### ISSUE TITLE
Possible bug in eval.py & question about visualization

### ISSUE THREAD

**Issue by kevin-so** [columbia-ai-robotics/semantic-abstraction#2]
Hi Huy,

Thanks for sharing your code! I believe there may be a bug in the evaluation code: in the provided CLI command for OVSSC on the NYU dataset, there's a flag `--merge_nyu_classes` that isn't included in the list of arguments under `utils.py::config_parser()`. Further, the NYU dataset comes with a `scc_split.pkl` file, but the `exp_dict` accepts a `vool_split.pkl` by [default](https://github.com/columbia-ai-robotics/semantic-abstraction/blob/main/eval.py#L41).  

I also wanted to confirm whether the example Habitat Matterport and ARKitScenes pickle files are included in the 269GB dataset? Under the visualization section, it's mentioned that those files should be provided under a folder named `scene_files`, but I don't seem to see it in the repository.

**Comment by huy-ha** [comment]
Thank you so much for your interest in our codebase and reporting all these issues!

> I believe there may be a bug in the evaluation code: in the provided CLI command for OVSSC on the NYU dataset, there's a flag --merge_nyu_classes that isn't included in the list of arguments under utils.py::config_parser()

I've removed the line from the README, it was used in my internal codebase to merge the full 894 classes to 11 classes. I didn't include it because it's quite messy, but if you're interested, shoot me an email, I'm happy to send what I have over.

> Further, the NYU dataset comes with a scc_split.pkl file, but the exp_dict accepts a vool_split.pkl by [default](https://github.com/columbia-ai-robotics/semantic-abstraction/blob/main/eval.py#L41)

Fixed!

> Under the visualization section, it's mentioned that those files should be provided under a folder named scene_files, but I don't seem to see it in the repository.

I've just pushed it! I didn't realized they were ignored by the `.gitignore`.
